# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Set work directory
WORKDIR /app

# Copy source code
COPY . /app

# Install pip dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -e .

# Expose port if needed, but MCP uses stdio transport

# Set entrypoint to run the MCP server
ENTRYPOINT ["python", "main.py"]
